### ISSUE TITLE
Kaart digitaal annoteren

### ISSUE THREAD

**Issue by clemens-tolboom** [KennisnetwerkDataScience/Wifi-punten-in-Leeuwarden#5]
Waar liggen welke punten met wifi punt

**Comment by whirlproductions** [comment]
9 sensor locaties + adressen (alleen Wirdumerpoortsbrug ontbreekt nog)
https://drive.google.com/open?id=1R4M217rNnuJ0gXYCChrsZbH126HLEc_n&usp=sharing

**Comment by clemens-tolboom** [comment]
Handige kaart. Met een mooie tabel erbij :-)

**Comment by JannekeArntzen** [comment]
De laatste sensor (Wirdumerpoortsbrug, sensorcode 1622) heeft als coördinaten:    
  53,1983 / 5,7969

**Comment by clemens-tolboom** [comment]
Dat maakt bij mij de set (waarbij ik nog de namen moet invullen blijkbaar)

| ID | Point | Name |
| --- | --- | --- |
| 1074 | POINT (5.794506 53.200509) | |
| 1078 | POINT (5.793081 53.200826) | |
| 1079 | POINT (5.797128 53.200347) | |
| 1625 | POINT (5.792219 53.199183) | |
| 1627 | POINT (5.793139 53.200104) | |
| 1631 | POINT (5.791639 53.202216) | |
| 1636 | POINT (5.796556 53.201777) | |
| 2054 | POINT (5.795879 53.199645) | |
| 2779 | POINT (5.799048 53.202032) | |
| 1622 | POINT (5.7969 53.1983) | Wirdumerpoortsbrug |
